name: Setup secrets
description: Set up secrets for build

runs:
  using: "composite"
  steps:
    - name: setup google-services.json
      shell: bash
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $GOOGLE_SERVICES_JSON | base64 --decode > app/google-services.json
